FROM node:20 as build
WORKDIR /frontend
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build

FROM ubuntu:24.04

RUN apt update -y \
    && apt install -y nginx curl vim\
    && apt-get install -y software-properties-common \
    && apt-get clean

EXPOSE 80
STOPSIGNAL SIGTERM
COPY  --from=build /frontend/dist /var/www/html

CMD [ "nginx", "-g", "daemon off;" ]