version: "3"
services:
  mongodb-learnaws:
    image: mongo
    container_name: mongodb-learnaws
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /learnaws/Documents/databases/mongodb/learnaws-data:/data/db
  backend-learnaws:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/
    container_name: backend-learnaws
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb-learnaws
  frontend-learnaws:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: frontend-learnaws
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-learnaws